# Intro
**This is Lesson 7 in the [Deep Learning](https://www.kaggle.com/learn/deep-learning) course**  

The models you've built so far have relied on pre-trained models.  But they aren't the ideal solution for many use cases.  In this lesson, you will learn how to build totally new models.

# Lesson


In [1]:
"""
Transfer Learning only takes you so far. An network trained on millions of photos is not applicable to something like identifying MRIs or picassos.
Hence we need to train our own classifier. Here we will train our dataset on a MNIST dataset, where the columns are index = label, and pixel(No) columns, where No refers to the number
We convert the one hot encoded version back into 28 x 28 images

Dropout: ignore randomly selected nodes for parts of training, basically preventing overfitting - by preventing more powerful nodes from possibly dominating the overall output
i.e. each convolution from previous layer must be ignored 50% of time by the following layer. WHEN YOU PREDICT HOWEVER, ALL NODES USED
"""

'\n\n'

Tra# Sample Code

In [5]:


import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from tensorflow.python import keras
from tensorflow.python.keras.models import Sequential
from tensorflow.python.keras.layers import Dense, Flatten, Conv2D, Dropout


img_rows, img_cols = 28, 28
num_classes = 10

#Since the raw here is a csv, and when we call dataPrep we've already read it, we can directly access the "label" cikynnb
def data_prep(raw):
    out_y = keras.utils.to_categorical(raw.label, num_classes)

    num_images = raw.shape[0] #Number of rows
        #Selecting values only, not the label (0-9, which is all in the firstcolumn)
    x_as_array = raw.values[:,1:] 
    print (x_as_array)
    print(raw.values[:,:] )
    x_shaped_array = x_as_array.reshape(num_images, img_rows, img_cols, 1)
    #Normalize by 255, which is the map pixel intensities
    out_x = x_shaped_array / 255
    return out_x, out_y

train_file = "../input/digit-recognizer/train.csv"
raw_data = pd.read_csv(train_file)

x, y = data_prep(raw_data)

model = Sequential()
#Arguments
#20 = number of convolutions/filters
#Size of pixels in that convolution filter or kernel_size
#Flatten is needed to convert into 1D representation
model.add(Conv2D(20, kernel_size=(3, 3),
                 activation='relu',
                 input_shape=(img_rows, img_cols, 1)))
model.add(Conv2D(20, kernel_size=(3, 3), activation='relu'))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dense(num_classes, activation='softmax'))

model.compile(loss=keras.losses.categorical_crossentropy,
              optimizer='adam',
              metrics=['accuracy'])
model.fit(x, y,
          batch_size=128,
          epochs=2,
          validation_split = 0.2)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [7 0 0 ... 0 0 0]
 [6 0 0 ... 0 0 0]
 [9 0 0 ... 0 0 0]]
Train on 33600 samples, validate on 8400 samples
Epoch 1/2
33600/33600 [==============================] - 35s 1ms/step - loss: 0.2369 - acc: 0.9316 - val_loss: 0.0856 - val_acc: 0.9739
Epoch 2/2
33600/33600 [==============================] - 34s 1ms/step - loss: 0.0631 - acc: 0.9809 - val_loss: 0.0575 - val_acc: 0.9813


# Your Turn
You are ready to **[build your own model](https://www.kaggle.com/kernels/fork/574269)**.

---
**[Deep Learning Course Home Page](https://www.kaggle.com/learn/deep-learning)**
